import {Icon} from '../../../shared/components/icon';

export const icons: {[kind: string]: Icon} = {
    ClusterRole: 'box',
    ConfigMap: 'bars',
    ClusterRoleBinding: 'link',
    CustomResourceDefinition: 'box',
    CronJob: 'clock',
    Deployment: 'sync-alt',
    DaemonSet: 'microchip',
    Endpoint: 'sitemap',
    Endpoints: 'sitemap',
    Group: 'users',
    HorizontalPodAutoscaler: 'microchip',
    Ingress: 'random',
    Job: 'th',
    LimitRange: 'box',
    NetworkPolicy: 'lock',
    Namespace: 'square',
    Pod: 'box',
    PodSecurityPolicy: 'lock',
    PersistentVolume: 'database',
    PersistentVolumeClaim: 'database',
    Quota: 'tachometer-alt',
    RoleBinding: 'user-shield',
    Role: 'shield-alt',
    ReplicaSet: 'copy',
    ServiceAccount: 'user',
    StorageClass: 'database',
    Secret: 'key',
    StatefulSet: 'database',
    Service: 'sitemap',
    User: 'user',
    Workflow: 'sitemap',
    Volume: 'box'
};
