apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        isDefault: true
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
