apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: postgres
type: Opaque
stringData:
  username: argo
  password: argo
  dsn: "postgresql://argo:argo@postgres:5432/argo?sslmode=disable"
