apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.7.2
        args: ["-config.file=/etc/tempo/tempo.yaml"]
        ports:
        - containerPort: 3200
          name: tempo-query
        volumeMounts:
        - name: config
          mountPath: /etc/tempo/tempo.yaml
          subPath: tempo.yaml
        - name: data
          mountPath: /var/tempo
      volumes:
      - name: config
        configMap:
          name: tempo-config
      - name: data
        emptyDir: {}
