apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
  - name: otlp-http
    port: 4318
    targetPort: 4318
  - name: tempo-query
    port: 3200
    targetPort: 3200
