apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - ../../base/crds/full
  - ../base/prometheus

components:
  - ../../components/otel-collector
  - ../../components/tempo
  - ../../components/grafana

patches:
  - path: overlays/workflow-controller-configmap.yaml
  - path: overlays/prometheus-deployment.yaml
