apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aggregated-apiserver-sqlite
  labels:
    app: argo-aggregated-apiserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
