#!/usr/bin/env python3

from gevent import monkey
monkey.patch_all()

from ax.util.az_patch import az_patch
az_patch()

from ax.devops.workflow.adc_entry import main
if __name__ == '__main__':
    main()
