/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GithubComArgoprojLabsArgoDataflowApiV1alpha1Code
 */
public class GithubComArgoprojLabsArgoDataflowApiV1alpha1CodeTest {
    private final GithubComArgoprojLabsArgoDataflowApiV1alpha1Code model = new GithubComArgoprojLabsArgoDataflowApiV1alpha1Code();

    /**
     * Model tests for GithubComArgoprojLabsArgoDataflowApiV1alpha1Code
     */
    @Test
    public void testGithubComArgoprojLabsArgoDataflowApiV1alpha1Code() {
        // TODO: test GithubComArgoprojLabsArgoDataflowApiV1alpha1Code
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'runtime'
     */
    @Test
    public void runtimeTest() {
        // TODO: test runtime
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

}
