/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojWorkflowV1alpha1Version
 */
public class IoArgoprojWorkflowV1alpha1VersionTest {
    private final IoArgoprojWorkflowV1alpha1Version model = new IoArgoprojWorkflowV1alpha1Version();

    /**
     * Model tests for IoArgoprojWorkflowV1alpha1Version
     */
    @Test
    public void testIoArgoprojWorkflowV1alpha1Version() {
        // TODO: test IoArgoprojWorkflowV1alpha1Version
    }

    /**
     * Test the property 'buildDate'
     */
    @Test
    public void buildDateTest() {
        // TODO: test buildDate
    }

    /**
     * Test the property 'compiler'
     */
    @Test
    public void compilerTest() {
        // TODO: test compiler
    }

    /**
     * Test the property 'gitCommit'
     */
    @Test
    public void gitCommitTest() {
        // TODO: test gitCommit
    }

    /**
     * Test the property 'gitTag'
     */
    @Test
    public void gitTagTest() {
        // TODO: test gitTag
    }

    /**
     * Test the property 'gitTreeState'
     */
    @Test
    public void gitTreeStateTest() {
        // TODO: test gitTreeState
    }

    /**
     * Test the property 'goVersion'
     */
    @Test
    public void goVersionTest() {
        // TODO: test goVersion
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
