/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1TriggerParameterSource;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojEventsV1alpha1TriggerParameter
 */
public class IoArgoprojEventsV1alpha1TriggerParameterTest {
    private final IoArgoprojEventsV1alpha1TriggerParameter model = new IoArgoprojEventsV1alpha1TriggerParameter();

    /**
     * Model tests for IoArgoprojEventsV1alpha1TriggerParameter
     */
    @Test
    public void testIoArgoprojEventsV1alpha1TriggerParameter() {
        // TODO: test IoArgoprojEventsV1alpha1TriggerParameter
    }

    /**
     * Test the property 'dest'
     */
    @Test
    public void destTest() {
        // TODO: test dest
    }

    /**
     * Test the property 'operation'
     */
    @Test
    public void operationTest() {
        // TODO: test operation
    }

    /**
     * Test the property 'src'
     */
    @Test
    public void srcTest() {
        // TODO: test src
    }

}
