/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1EventSourceFilter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IoArgoprojEventsV1alpha1AzureEventsHubEventSource
 */
public class IoArgoprojEventsV1alpha1AzureEventsHubEventSourceTest {
    private final IoArgoprojEventsV1alpha1AzureEventsHubEventSource model = new IoArgoprojEventsV1alpha1AzureEventsHubEventSource();

    /**
     * Model tests for IoArgoprojEventsV1alpha1AzureEventsHubEventSource
     */
    @Test
    public void testIoArgoprojEventsV1alpha1AzureEventsHubEventSource() {
        // TODO: test IoArgoprojEventsV1alpha1AzureEventsHubEventSource
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'fqdn'
     */
    @Test
    public void fqdnTest() {
        // TODO: test fqdn
    }

    /**
     * Test the property 'hubName'
     */
    @Test
    public void hubNameTest() {
        // TODO: test hubName
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'sharedAccessKey'
     */
    @Test
    public void sharedAccessKeyTest() {
        // TODO: test sharedAccessKey
    }

    /**
     * Test the property 'sharedAccessKeyName'
     */
    @Test
    public void sharedAccessKeyNameTest() {
        // TODO: test sharedAccessKeyName
    }

}
