// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkflowArtifactGCTaskSets implements WorkflowArtifactGCTaskSetInterface
type FakeWorkflowArtifactGCTaskSets struct {
	Fake *FakeArgoprojV1alpha1
	ns   string
}

var workflowartifactgctasksetsResource = schema.GroupVersionResource{Group: "argoproj.io", Version: "v1alpha1", Resource: "workflowartifactgctasksets"}

var workflowartifactgctasksetsKind = schema.GroupVersionKind{Group: "argoproj.io", Version: "v1alpha1", Kind: "WorkflowArtifactGCTaskSet"}

// Get takes name of the workflowArtifactGCTaskSet, and returns the corresponding workflowArtifactGCTaskSet object, and an error if there is any.
func (c *FakeWorkflowArtifactGCTaskSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WorkflowArtifactGCTaskSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workflowartifactgctasksetsResource, c.ns, name), &v1alpha1.WorkflowArtifactGCTaskSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowArtifactGCTaskSet), err
}

// List takes label and field selectors, and returns the list of WorkflowArtifactGCTaskSets that match those selectors.
func (c *FakeWorkflowArtifactGCTaskSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WorkflowArtifactGCTaskSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workflowartifactgctasksetsResource, workflowartifactgctasksetsKind, c.ns, opts), &v1alpha1.WorkflowArtifactGCTaskSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WorkflowArtifactGCTaskSetList{ListMeta: obj.(*v1alpha1.WorkflowArtifactGCTaskSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.WorkflowArtifactGCTaskSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workflowArtifactGCTaskSets.
func (c *FakeWorkflowArtifactGCTaskSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workflowartifactgctasksetsResource, c.ns, opts))

}

// Create takes the representation of a workflowArtifactGCTaskSet and creates it.  Returns the server's representation of the workflowArtifactGCTaskSet, and an error, if there is any.
func (c *FakeWorkflowArtifactGCTaskSets) Create(ctx context.Context, workflowArtifactGCTaskSet *v1alpha1.WorkflowArtifactGCTaskSet, opts v1.CreateOptions) (result *v1alpha1.WorkflowArtifactGCTaskSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workflowartifactgctasksetsResource, c.ns, workflowArtifactGCTaskSet), &v1alpha1.WorkflowArtifactGCTaskSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowArtifactGCTaskSet), err
}

// Update takes the representation of a workflowArtifactGCTaskSet and updates it. Returns the server's representation of the workflowArtifactGCTaskSet, and an error, if there is any.
func (c *FakeWorkflowArtifactGCTaskSets) Update(ctx context.Context, workflowArtifactGCTaskSet *v1alpha1.WorkflowArtifactGCTaskSet, opts v1.UpdateOptions) (result *v1alpha1.WorkflowArtifactGCTaskSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workflowartifactgctasksetsResource, c.ns, workflowArtifactGCTaskSet), &v1alpha1.WorkflowArtifactGCTaskSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowArtifactGCTaskSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkflowArtifactGCTaskSets) UpdateStatus(ctx context.Context, workflowArtifactGCTaskSet *v1alpha1.WorkflowArtifactGCTaskSet, opts v1.UpdateOptions) (*v1alpha1.WorkflowArtifactGCTaskSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(workflowartifactgctasksetsResource, "status", c.ns, workflowArtifactGCTaskSet), &v1alpha1.WorkflowArtifactGCTaskSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowArtifactGCTaskSet), err
}

// Delete takes name of the workflowArtifactGCTaskSet and deletes it. Returns an error if one occurs.
func (c *FakeWorkflowArtifactGCTaskSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(workflowartifactgctasksetsResource, c.ns, name), &v1alpha1.WorkflowArtifactGCTaskSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkflowArtifactGCTaskSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workflowartifactgctasksetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkflowArtifactGCTaskSetList{})
	return err
}

// Patch applies the patch and returns the patched workflowArtifactGCTaskSet.
func (c *FakeWorkflowArtifactGCTaskSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WorkflowArtifactGCTaskSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workflowartifactgctasksetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.WorkflowArtifactGCTaskSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowArtifactGCTaskSet), err
}
