// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	info "github.com/argoproj/argo/pkg/apiclient/info"
	mock "github.com/stretchr/testify/mock"
)

// InfoServiceServer is an autogenerated mock type for the InfoServiceServer type
type InfoServiceServer struct {
	mock.Mock
}

// GetInfo provides a mock function with given fields: _a0, _a1
func (_m *InfoServiceServer) GetInfo(_a0 context.Context, _a1 *info.GetInfoRequest) (*info.InfoResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *info.InfoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *info.GetInfoRequest) *info.InfoResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*info.InfoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *info.GetInfoRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
