/*
 * Argo
 * Workflow Service API performs CRUD actions against application resources
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.argo.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.argo.client.model.V1alpha1CronWorkflow;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CronworkflowUpdateCronWorkflowRequest
 */
public class CronworkflowUpdateCronWorkflowRequestTest {
    private final CronworkflowUpdateCronWorkflowRequest model = new CronworkflowUpdateCronWorkflowRequest();

    /**
     * Model tests for CronworkflowUpdateCronWorkflowRequest
     */
    @Test
    public void testCronworkflowUpdateCronWorkflowRequest() {
        // TODO: test CronworkflowUpdateCronWorkflowRequest
    }

    /**
     * Test the property 'cronWorkflow'
     */
    @Test
    public void cronWorkflowTest() {
        // TODO: test cronWorkflow
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

}
