/*
 * Argo Server API
 * The Argo Server based API for Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.argo.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V1AzureFileVolumeSource
 */
public class V1AzureFileVolumeSourceTest {
    private final V1AzureFileVolumeSource model = new V1AzureFileVolumeSource();

    /**
     * Model tests for V1AzureFileVolumeSource
     */
    @Test
    public void testV1AzureFileVolumeSource() {
        // TODO: test V1AzureFileVolumeSource
    }

    /**
     * Test the property 'readOnly'
     */
    @Test
    public void readOnlyTest() {
        // TODO: test readOnly
    }

    /**
     * Test the property 'secretName'
     */
    @Test
    public void secretNameTest() {
        // TODO: test secretName
    }

    /**
     * Test the property 'shareName'
     */
    @Test
    public void shareNameTest() {
        // TODO: test shareName
    }

}
