/*
 * Argo Server API
 * The Argo Server based API for Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.argo.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.argo.client.model.V1ExecAction;
import io.argoproj.argo.client.model.V1HTTPGetAction;
import io.argoproj.argo.client.model.V1TCPSocketAction;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V1Handler
 */
public class V1HandlerTest {
    private final V1Handler model = new V1Handler();

    /**
     * Model tests for V1Handler
     */
    @Test
    public void testV1Handler() {
        // TODO: test V1Handler
    }

    /**
     * Test the property 'exec'
     */
    @Test
    public void execTest() {
        // TODO: test exec
    }

    /**
     * Test the property 'httpGet'
     */
    @Test
    public void httpGetTest() {
        // TODO: test httpGet
    }

    /**
     * Test the property 'tcpSocket'
     */
    @Test
    public void tcpSocketTest() {
        // TODO: test tcpSocket
    }

}
