/*
 * Argo Server API
 * The Argo Server based API for Argo
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.argo.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.argo.client.model.V1Handler;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for V1Probe
 */
public class V1ProbeTest {
    private final V1Probe model = new V1Probe();

    /**
     * Model tests for V1Probe
     */
    @Test
    public void testV1Probe() {
        // TODO: test V1Probe
    }

    /**
     * Test the property 'failureThreshold'
     */
    @Test
    public void failureThresholdTest() {
        // TODO: test failureThreshold
    }

    /**
     * Test the property 'handler'
     */
    @Test
    public void handlerTest() {
        // TODO: test handler
    }

    /**
     * Test the property 'initialDelaySeconds'
     */
    @Test
    public void initialDelaySecondsTest() {
        // TODO: test initialDelaySeconds
    }

    /**
     * Test the property 'periodSeconds'
     */
    @Test
    public void periodSecondsTest() {
        // TODO: test periodSeconds
    }

    /**
     * Test the property 'successThreshold'
     */
    @Test
    public void successThresholdTest() {
        // TODO: test successThreshold
    }

    /**
     * Test the property 'timeoutSeconds'
     */
    @Test
    public void timeoutSecondsTest() {
        // TODO: test timeoutSeconds
    }

}
