#!/bin/sh
set -eu

m=30

if find dist/pre-commit -mmin -$m | grep .; then
  echo '✅ `make pre-commit -B` was run in the last ${m}m'
else
  echo 'ℹ️ `make pre-commit -B` was not run within the last ${m}m, running now'
  make pre-commit -B
fi

if find dist/test -mmin -${m} | grep .; then
  echo '✅ `make test` was run in the last ${m}m'
else
  echo 'ℹ️ `make test` was not run within the last ${m}m, running now'
  make test
fi