"""
    Argo Server API

    You can get examples of requests and responses by using the CLI with `--gloglevel=9`, e.g. `argo list --gloglevel=9`  # noqa: E501

    The version of the OpenAPI document: VERSION
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from io.argoproj.workflow.apis.sensor_service_api import SensorServiceApi  # noqa: E501


class TestSensorServiceApi(unittest.TestCase):
    """SensorServiceApi unit test stubs"""

    def setUp(self):
        self.api = SensorServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sensor_service_create_sensor(self):
        """Test case for sensor_service_create_sensor

        """
        pass

    def test_sensor_service_delete_sensor(self):
        """Test case for sensor_service_delete_sensor

        """
        pass

    def test_sensor_service_get_sensor(self):
        """Test case for sensor_service_get_sensor

        """
        pass

    def test_sensor_service_list_sensors(self):
        """Test case for sensor_service_list_sensors

        """
        pass

    def test_sensor_service_sensors_logs(self):
        """Test case for sensor_service_sensors_logs

        """
        pass

    def test_sensor_service_update_sensor(self):
        """Test case for sensor_service_update_sensor

        """
        pass

    def test_sensor_service_watch_sensors(self):
        """Test case for sensor_service_watch_sensors

        """
        pass


if __name__ == '__main__':
    unittest.main()
