apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
data:
  default-v1: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: ministack:4566
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
  my-key: |
    archiveLogs: true
    s3:
      bucket: my-bucket
      endpoint: ministack:4566
      insecure: true
      accessKeySecret:
        name: my-minio-cred
        key: accesskey
      secretKeySecret:
        name: my-minio-cred
        key: secretkey
