/*
 * Argo Workflows API
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.workflow.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.workflow.models.IoArgoprojEventsV1alpha1EventSourceFilter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * PubSubEventSource refers to event-source for GCP PubSub related events.
 */
@ApiModel(description = "PubSubEventSource refers to event-source for GCP PubSub related events.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IoArgoprojEventsV1alpha1PubSubEventSource {
  public static final String SERIALIZED_NAME_CREDENTIAL_SECRET = "credentialSecret";
  @SerializedName(SERIALIZED_NAME_CREDENTIAL_SECRET)
  private io.kubernetes.client.openapi.models.V1SecretKeySelector credentialSecret;

  public static final String SERIALIZED_NAME_DELETE_SUBSCRIPTION_ON_FINISH = "deleteSubscriptionOnFinish";
  @SerializedName(SERIALIZED_NAME_DELETE_SUBSCRIPTION_ON_FINISH)
  private Boolean deleteSubscriptionOnFinish;

  public static final String SERIALIZED_NAME_FILTER = "filter";
  @SerializedName(SERIALIZED_NAME_FILTER)
  private IoArgoprojEventsV1alpha1EventSourceFilter filter;

  public static final String SERIALIZED_NAME_JSON_BODY = "jsonBody";
  @SerializedName(SERIALIZED_NAME_JSON_BODY)
  private Boolean jsonBody;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, String> metadata = null;

  public static final String SERIALIZED_NAME_PROJECT_I_D = "projectID";
  @SerializedName(SERIALIZED_NAME_PROJECT_I_D)
  private String projectID;

  public static final String SERIALIZED_NAME_SUBSCRIPTION_I_D = "subscriptionID";
  @SerializedName(SERIALIZED_NAME_SUBSCRIPTION_I_D)
  private String subscriptionID;

  public static final String SERIALIZED_NAME_TOPIC = "topic";
  @SerializedName(SERIALIZED_NAME_TOPIC)
  private String topic;

  public static final String SERIALIZED_NAME_TOPIC_PROJECT_I_D = "topicProjectID";
  @SerializedName(SERIALIZED_NAME_TOPIC_PROJECT_I_D)
  private String topicProjectID;


  public IoArgoprojEventsV1alpha1PubSubEventSource credentialSecret(io.kubernetes.client.openapi.models.V1SecretKeySelector credentialSecret) {
    
    this.credentialSecret = credentialSecret;
    return this;
  }

   /**
   * Get credentialSecret
   * @return credentialSecret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.kubernetes.client.openapi.models.V1SecretKeySelector getCredentialSecret() {
    return credentialSecret;
  }


  public void setCredentialSecret(io.kubernetes.client.openapi.models.V1SecretKeySelector credentialSecret) {
    this.credentialSecret = credentialSecret;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource deleteSubscriptionOnFinish(Boolean deleteSubscriptionOnFinish) {
    
    this.deleteSubscriptionOnFinish = deleteSubscriptionOnFinish;
    return this;
  }

   /**
   * Get deleteSubscriptionOnFinish
   * @return deleteSubscriptionOnFinish
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDeleteSubscriptionOnFinish() {
    return deleteSubscriptionOnFinish;
  }


  public void setDeleteSubscriptionOnFinish(Boolean deleteSubscriptionOnFinish) {
    this.deleteSubscriptionOnFinish = deleteSubscriptionOnFinish;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource filter(IoArgoprojEventsV1alpha1EventSourceFilter filter) {
    
    this.filter = filter;
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public IoArgoprojEventsV1alpha1EventSourceFilter getFilter() {
    return filter;
  }


  public void setFilter(IoArgoprojEventsV1alpha1EventSourceFilter filter) {
    this.filter = filter;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource jsonBody(Boolean jsonBody) {
    
    this.jsonBody = jsonBody;
    return this;
  }

   /**
   * Get jsonBody
   * @return jsonBody
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getJsonBody() {
    return jsonBody;
  }


  public void setJsonBody(Boolean jsonBody) {
    this.jsonBody = jsonBody;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public IoArgoprojEventsV1alpha1PubSubEventSource putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getMetadata() {
    return metadata;
  }


  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource projectID(String projectID) {
    
    this.projectID = projectID;
    return this;
  }

   /**
   * Get projectID
   * @return projectID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProjectID() {
    return projectID;
  }


  public void setProjectID(String projectID) {
    this.projectID = projectID;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource subscriptionID(String subscriptionID) {
    
    this.subscriptionID = subscriptionID;
    return this;
  }

   /**
   * Get subscriptionID
   * @return subscriptionID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSubscriptionID() {
    return subscriptionID;
  }


  public void setSubscriptionID(String subscriptionID) {
    this.subscriptionID = subscriptionID;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource topic(String topic) {
    
    this.topic = topic;
    return this;
  }

   /**
   * Get topic
   * @return topic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTopic() {
    return topic;
  }


  public void setTopic(String topic) {
    this.topic = topic;
  }


  public IoArgoprojEventsV1alpha1PubSubEventSource topicProjectID(String topicProjectID) {
    
    this.topicProjectID = topicProjectID;
    return this;
  }

   /**
   * Get topicProjectID
   * @return topicProjectID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTopicProjectID() {
    return topicProjectID;
  }


  public void setTopicProjectID(String topicProjectID) {
    this.topicProjectID = topicProjectID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IoArgoprojEventsV1alpha1PubSubEventSource ioArgoprojEventsV1alpha1PubSubEventSource = (IoArgoprojEventsV1alpha1PubSubEventSource) o;
    return Objects.equals(this.credentialSecret, ioArgoprojEventsV1alpha1PubSubEventSource.credentialSecret) &&
        Objects.equals(this.deleteSubscriptionOnFinish, ioArgoprojEventsV1alpha1PubSubEventSource.deleteSubscriptionOnFinish) &&
        Objects.equals(this.filter, ioArgoprojEventsV1alpha1PubSubEventSource.filter) &&
        Objects.equals(this.jsonBody, ioArgoprojEventsV1alpha1PubSubEventSource.jsonBody) &&
        Objects.equals(this.metadata, ioArgoprojEventsV1alpha1PubSubEventSource.metadata) &&
        Objects.equals(this.projectID, ioArgoprojEventsV1alpha1PubSubEventSource.projectID) &&
        Objects.equals(this.subscriptionID, ioArgoprojEventsV1alpha1PubSubEventSource.subscriptionID) &&
        Objects.equals(this.topic, ioArgoprojEventsV1alpha1PubSubEventSource.topic) &&
        Objects.equals(this.topicProjectID, ioArgoprojEventsV1alpha1PubSubEventSource.topicProjectID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credentialSecret, deleteSubscriptionOnFinish, filter, jsonBody, metadata, projectID, subscriptionID, topic, topicProjectID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IoArgoprojEventsV1alpha1PubSubEventSource {\n");
    sb.append("    credentialSecret: ").append(toIndentedString(credentialSecret)).append("\n");
    sb.append("    deleteSubscriptionOnFinish: ").append(toIndentedString(deleteSubscriptionOnFinish)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    jsonBody: ").append(toIndentedString(jsonBody)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    projectID: ").append(toIndentedString(projectID)).append("\n");
    sb.append("    subscriptionID: ").append(toIndentedString(subscriptionID)).append("\n");
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    topicProjectID: ").append(toIndentedString(topicProjectID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

