# Dockerfile for event trigger

FROM %%BUILDER_IMAGE_ID%%

ENV PYTHONPATH=/ax/src
COPY docker_build/src /ax/src

COPY axeventtrigger.py /ax/bin/axeventtrigger
COPY run.sh /ax/bin/run.sh
RUN chmod +x /ax/bin/run.sh

CMD /ax/bin/run.sh