/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argoproj.github.io/argo-workflows/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IoArgoprojWorkflowV1alpha1Histogram : Histogram is a Histogram prometheus metric



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoArgoprojWorkflowV1alpha1Histogram {
    /// Buckets is a list of bucket divisors for the histogram
    #[serde(rename = "buckets")]
    pub buckets: Vec<f32>,
    /// Value is the value of the metric
    #[serde(rename = "value")]
    pub value: String,
}

impl IoArgoprojWorkflowV1alpha1Histogram {
    /// Histogram is a Histogram prometheus metric
    pub fn new(buckets: Vec<f32>, value: String) -> IoArgoprojWorkflowV1alpha1Histogram {
        IoArgoprojWorkflowV1alpha1Histogram {
            buckets,
            value,
        }
    }
}


