name: Dev Container

on:
  push:
    paths:
      - ".devcontainer/**"
      - "hack/k8s-versions.sh"
      - ".github/workflows/devcontainer.yaml"
    branches:
      - main
  pull_request:
    paths:
      - ".devcontainer/**"
      - "hack/k8s-versions.sh"
      - ".github/workflows/devcontainer.yaml"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.repository == 'argoproj/argo-workflows'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
        with:
          # Workaround for segfaults under arm64:
          # https://github.com/docker/setup-qemu-action/issues/198#issuecomment-2653791775
          image: tonistiigi/binfmt:qemu-v7.0.0-28
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Login to registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
      - name: Build dev container image
        run: make devcontainer-build
        env:
          TARGET_PLATFORM: linux/amd64,linux/arm64
          DEVCONTAINER_PUSH: ${{ github.event_name == 'push' && 'true' || 'false' }}
