name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.9
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.26"
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"
      # This is mainly here so the dependencies get saved to the cache by "actions/setup-go"
      - name: Download go dependencies
        run: go mod download
      # Use the same make target both locally and on CI to make it easier to debug failures.
      - name: Build & Lint docs
        run: make docs
      # If linters auto-fix issues, files will be changed. If so, fail the build.
      - name: Check if linters made changes
        run: git diff --exit-code
      # Upload the site so reviewers see it.
      - name: Upload Docs Site
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docs
          path: site
          if-no-files-found: error
