name: PR Feature Check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  feature-pr-handling:
    runs-on: ubuntu-24.04
    steps:
      - name: Check if feature PR
        id: check-type
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ "$PR_TITLE" =~ ^feat(\(.*\))?!?:\ .+ ]]; then
            echo "is_feat=true" >> "$GITHUB_OUTPUT"
          fi

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        if: steps.check-type.outputs.is_feat == 'true'
        with:
          go-version: "1.25"
          cache: true
      - name: Checkout
        if: steps.check-type.outputs.is_feat == 'true'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 50

      - name: Ensure ./.features/pending/*.md addition(s)
        if: steps.check-type.outputs.is_feat == 'true'
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            .features/pending/*.md

      - name: No ./.features/*.md addition
        if: steps.check-type.outputs.is_feat == 'true' && steps.changed-files.outputs.added_files_count == 0
        run: |
          echo "No feature description was added to the ./.features/pending/ directory for this feature PR."
          echo "Please add a .md file to the ./.features/pending/ directory."
          echo "See docs/running-locally.md for more details."
          false

      - name: Validate ./.features/*.md changes
        if: steps.check-type.outputs.is_feat == 'true' && steps.changed-files.outputs.added_files_count > 0
        run: |
          echo "A feature description was added to the ./.features/ directory."
          make features-validate \
            || { echo "New ./.features/*.md file failed validation."; exit 1; }
