name: PR Title Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  title-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check PR Title's semantic conformance
        id: semantic-pr-check
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
